*&---------------------------------------------------------------------*
*&  Include           Z_REPORTE_SEL
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK blk1  WITH FRAME TITLE title1.
SELECT-OPTIONS: s_fecha FOR sy-datum NO INTERVALS NO-EXTENSION OBLIGATORY DEFAULT sy-datum,
                s_clien FOR zbc_clientesdm-codigo NO INTERVALS NO-EXTENSION OBLIGATORY DEFAULT 'NVS'.
*                s_sist  syst-sysid NO INTERVALS NO-EXTENSION OBLIGATORY.
PARAMETERS: p_sist  TYPE syst-sysid OBLIGATORY DEFAULT 'DEC',
            p_langu TYPE sy-langu OBLIGATORY DEFAULT 'S'.
SELECTION-SCREEN BEGIN OF LINE .
SELECTION-SCREEN COMMENT (30) TEXT-015.
PARAMETERS vista_h RADIOBUTTON GROUP g1 DEFAULT 'X'.
SELECTION-SCREEN COMMENT (10) TEXT-016.
PARAMETERS vista_v RADIOBUTTON GROUP g1 .
SELECTION-SCREEN COMMENT (10) TEXT-017.
SELECTION-SCREEN END OF LINE.
*                s_mand  FOR zbc_tiposistdm-mandt NO INTERVALS NO-EXTENSION OBLIGATORY.
SELECTION-SCREEN END OF BLOCK blk1.
SELECTION-SCREEN BEGIN OF BLOCK blk2_1  WITH FRAME TITLE title2_1. " Datos AGR_1251
SELECT-OPTIONS: s_agr    FOR agr_define-agr_name,
                s_object FOR agr_1251-object,
                s_auth   FOR agr_1251-auth,
*                s_varian FOR agr_1251-variant,
                s_field  FOR agr_1251-field,
                s_low    FOR agr_1251-low,
                s_high   FOR agr_1251-high.
SELECTION-SCREEN END OF BLOCK blk2_1.
SELECTION-SCREEN BEGIN OF BLOCK blk2_2  WITH FRAME TITLE title2_2. " Datos USR02
SELECT-OPTIONS: s_user  FOR usr02-bname DEFAULT 'DELOITTE',
                s_ustyp FOR usr02-ustyp,
                s_grupo FOR suid_st_node_logondata-class.
*                s_objau FOR tobj-objct.

SELECTION-SCREEN BEGIN OF LINE .
SELECTION-SCREEN COMMENT (32) TEXT-005.
PARAMETERS p_cb_baj AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT (10) TEXT-003. " Bajo
PARAMETERS p_cb_med AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT (10) TEXT-001. " Medio
PARAMETERS p_cb_alt AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT (10) TEXT-002. " Alto
PARAMETERS p_cb_cri AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT (10) TEXT-004. " Critico
SELECTION-SCREEN END OF LINE.

*SELECT-OPTIONS: s_rol FOR agr_users-agr_name,
*                s_perfil FOR usr10-profn,
*                s_valaut FOR ust12-objct,
*                s_tx FOR tstc-tcode NO INTERVALS NO-EXTENSION.
SELECTION-SCREEN END OF BLOCK blk2_2.

SELECTION-SCREEN BEGIN OF BLOCK blk3  WITH FRAME TITLE title3. " 'Analisis de riesgo'.
SELECTION-SCREEN BEGIN OF LINE .
PARAMETERS p_cb_sf RADIOBUTTON GROUP g2 DEFAULT 'X'. "segregación de funciones.
SELECTION-SCREEN COMMENT (45) TEXT-014.
PARAMETERS p_cb_rt RADIOBUTTON GROUP g2. "analisis de riesgo tecnico.
SELECTION-SCREEN COMMENT (30) TEXT-013.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK blk3.


SELECTION-SCREEN BEGIN OF BLOCK blk4  WITH FRAME TITLE title4. " 'Tipo de análisis'.
SELECTION-SCREEN BEGIN OF LINE .
PARAMETERS p_cb_rol RADIOBUTTON GROUP g3.
SELECTION-SCREEN COMMENT (10) TEXT-006.
PARAMETERS p_cb_per RADIOBUTTON GROUP g3.
SELECTION-SCREEN COMMENT (10) TEXT-007.
PARAMETERS p_cb_usu RADIOBUTTON GROUP g3 DEFAULT 'X'.
SELECTION-SCREEN COMMENT (10) TEXT-008.
PARAMETERS p_cb_ocr RADIOBUTTON GROUP g3.
SELECTION-SCREEN COMMENT (25) TEXT-009.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK blk4.

SELECTION-SCREEN BEGIN OF BLOCK blk5  WITH FRAME TITLE title5. " 'Detalle Usuario / Transacción'.
SELECTION-SCREEN BEGIN OF LINE .
PARAMETERS p_cb_ub AS CHECKBOX DEFAULT ''.
SELECTION-SCREEN COMMENT (20) TEXT-010. "
PARAMETERS p_cb_ua AS CHECKBOX DEFAULT ''.
SELECTION-SCREEN COMMENT (20) TEXT-011. "
PARAMETERS p_cb_uv AS CHECKBOX DEFAULT ''.
SELECTION-SCREEN COMMENT (20) TEXT-012. "
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK blk5.

SELECTION-SCREEN BEGIN OF BLOCK blk6  WITH FRAME TITLE title6. "
SELECTION-SCREEN:
  PUSHBUTTON 1(50) but1 USER-COMMAND f11  VISIBLE LENGTH 30, "'Botón monitor'.
  PUSHBUTTON 60(50) but2 USER-COMMAND f02  VISIBLE LENGTH 30. "'Botón monitor'.
SELECTION-SCREEN END OF BLOCK blk6.
